spring:
  datasource:
    url: jdbc:mysql://localhost:3306/autumn?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  charset:
    console: utf-8
  level:
    root: info
    com.autumn.*: debug



